service: todo_list

image: gabrielgatti7/todo_list

servers:
  web:
    - 147.15.14.6

proxy:
  ssl: false

registry:
  username: gabrielgatti7
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: ubuntu
  keys:
    - ~/.ssh/oracle.key

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    RAILS_ENV: production
    SOLID_QUEUE_IN_PUMA: true

volumes:
  - "todo_list_storage:/rails/storage"

builder:
  arch: amd64